### ISSUE TITLE
Errors on first run

### ISSUE THREAD

**Issue by mikecann** [jacob-ebey/remix-cloudflare-demo#3]
If you clone then install and run `yarn dev` then you get a whole bunch of errors:

```shell
yarn run v1.22.4
$ cross-env NODE_ENV=development concurrently "npm:dev:*"
[dev:*remix] 
[dev:*remix] > dev:remix
[dev:*remix] > remix watch
[dev:*remix]
[dev:*cypress]
[dev:*cypress] > dev:cypress
[dev:*cypress] > cypress open
[dev:*cypress]
[dev:*miniflare]
[dev:*miniflare] > dev:miniflare
[dev:*miniflare] > miniflare --kv REDIRECTS --kv-persist --build-command "npx ts-node ./build.ts" --disable-cache --watch
[dev:*miniflare]
[dev:*tailwind]
[dev:*tailwind] > dev:tailwind
[dev:*tailwind] > tailwindcss -o app/styles/tailwind.css --watch
[dev:*tailwind]
[dev:*remix] Watching Remix app in development mode...
[dev:*cypress] It looks like this is your first time using Cypress: 8.7.0
[dev:*cypress]
[dev:*cypress] [STARTED] Task without title.
[dev:*remix] 
[dev:*remix]  > route-module:C:\dev\me\remix-cloudflare-demo\app\root.tsx:21:30: error: Could not resolve "./styles/tailwind.css"    
[dev:*remix]     21 │ import tailwindStylesUrl from "./styles/tailwind.css";
[dev:*remix]        ╵                               ~~~~~~~~~~~~~~~~~~~~~~~
[dev:*remix] 
[dev:*remix]
[dev:*remix] Build failed with 1 error:
[dev:*remix] route-module:C:\dev\me\remix-cloudflare-demo\app\root.tsx:21:30: error: Could not resolve "./styles/tailwind.css"       
[dev:*remix] 💿 Built in 879ms
[dev:*cypress] [TITLE]  Verified Cypress! C:\Users\mikec\AppData\Local\Cypress\Cache\8.7.0\Cypress
[dev:*cypress] [SUCCESS]  Verified Cypress! C:\Users\mikec\AppData\Local\Cypress\Cache\8.7.0\Cypress
[dev:*cypress]
[dev:*cypress] Opening Cypress...
[dev:*cypress] 
[dev:*tailwind] 
[dev:*tailwind] warn - You have enabled the JIT engine which is currently in preview.
[dev:*tailwind] warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.       
[dev:*tailwind]
[dev:*tailwind] Rebuilding...
[dev:*tailwind] 
[dev:*tailwind] 🌼 daisyUI components 1.16.6  https://github.com/saadeghi/daisyui
[dev:*tailwind]   ✔︎ Including:  base, components, themes[22], utilities
[dev:*tailwind]
[dev:*tailwind] Done in 325ms.
[dev:*remix] 💿 File created: app\styles\tailwind.css
[dev:*miniflare] [Worker] Running esbuild in development mode
[dev:*miniflare]  > worker/index.ts:5:23: error: Could not resolve "../build/index.js"
[dev:*miniflare]     5 │ import * as build from "../build/index.js";
[dev:*miniflare]       ╵                        ~~~~~~~~~~~~~~~~~~~
[dev:*miniflare]
[dev:*miniflare] C:\dev\me\remix-cloudflare-demo\node_modules\esbuild\lib\main.js:1493
[dev:*miniflare]   let error = new Error(`${text}${summary}`);
[dev:*miniflare]               ^
[dev:*miniflare] Error: Build failed with 1 error:
[dev:*miniflare] worker/index.ts:5:23: error: Could not resolve "../build/index.js"
[dev:*miniflare]     at failureErrorWithLog (C:\dev\me\remix-cloudflare-demo\node_modules\esbuild\lib\main.js:1493:15)
[dev:*miniflare]     at C:\dev\me\remix-cloudflare-demo\node_modules\esbuild\lib\main.js:1151:28
[dev:*miniflare]     at runOnEndCallbacks (C:\dev\me\remix-cloudflare-demo\node_modules\esbuild\lib\main.js:1069:65)
[dev:*miniflare]     at buildResponseToResult (C:\dev\me\remix-cloudflare-demo\node_modules\esbuild\lib\main.js:1149:7)
[dev:*miniflare]     at C:\dev\me\remix-cloudflare-demo\node_modules\esbuild\lib\main.js:1258:14
[dev:*miniflare]     at C:\dev\me\remix-cloudflare-demo\node_modules\esbuild\lib\main.js:629:9
[dev:*miniflare]     at handleIncomingPacket (C:\dev\me\remix-cloudflare-demo\node_modules\esbuild\lib\main.js:726:9)
[dev:*miniflare]     at Socket.readFromStdout (C:\dev\me\remix-cloudflare-demo\node_modules\esbuild\lib\main.js:596:7)
[dev:*miniflare]     at Socket.emit (node:events:394:28)
[dev:*miniflare]     at Socket.emit (node:domain:475:12) {
[dev:*miniflare]   errors: [
[dev:*miniflare]     {
[dev:*miniflare]       detail: undefined,
[dev:*miniflare]       location: [Object],
[dev:*miniflare]       notes: [],
[dev:*miniflare]       pluginName: '',
[dev:*miniflare]       text: 'Could not resolve "../build/index.js"'
[dev:*miniflare]     }
[dev:*miniflare]   ],
[dev:*miniflare]   warnings: []
[dev:*miniflare] }
[dev:*remix] 💿 Rebuilding...
[dev:*miniflare] [mf:err] Build failed with exit code 1
[dev:*miniflare] [mf:err] Unable to read worker.js: Error: ENOENT: no such file or directory, open 'C:\dev\me\remix-cloudflare-demo\worker.js' (defaulting to empty string)
[dev:*miniflare] [mf:inf] Worker reloaded! (0B)
[dev:*miniflare] [mf:inf] Listening on :8787
[dev:*miniflare] [mf:inf] - http://172.21.0.1:8787
[dev:*miniflare] [mf:inf] - http://192.168.86.161:8787
[dev:*miniflare] [mf:inf] - http://192.168.216.1:8787
[dev:*miniflare] [mf:inf] - http://192.168.222.1:8787
[dev:*miniflare] [mf:inf] - http://127.0.0.1:8787
[dev:*remix] 💿 Rebuilt in 99ms
```

If you `yarn dev` again then there are no more errors.

Not a big issue but I thought I would raise it.

**Comment by mikecann** [comment]
Addendum, you also get other errors if you try to make a change then refresh.

```shell
yarn run v1.22.4
$ cross-env NODE_ENV=development concurrently "npm:dev:*"
[dev:*cypress] 
[dev:*cypress] > dev:cypress
[dev:*cypress] > cypress open
[dev:*cypress]
[dev:*remix] 
[dev:*remix] > dev:remix
[dev:*remix] > remix watch
[dev:*remix]
[dev:*miniflare]
[dev:*miniflare] > dev:miniflare
[dev:*miniflare] > miniflare --kv REDIRECTS --kv-persist --build-command "npx ts-node ./build.ts" --disable-cache --watch
[dev:*miniflare]
[dev:*tailwind]
[dev:*tailwind] > dev:tailwind
[dev:*tailwind] > tailwindcss -o app/styles/tailwind.css --watch
[dev:*tailwind]
[dev:*remix] Watching Remix app in development mode...
[dev:*cypress] 
[dev:*tailwind] 
[dev:*tailwind] warn - You have enabled the JIT engine which is currently in preview.
[dev:*tailwind] warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.       
[dev:*tailwind]
[dev:*tailwind] Rebuilding...
[dev:*remix] 💿 Built in 453ms
[dev:*tailwind] 
[dev:*tailwind] 🌼 daisyUI components 1.16.6  https://github.com/saadeghi/daisyui
[dev:*tailwind]   ✔︎ Including:  base, components, themes[22], utilities
[dev:*tailwind]
[dev:*tailwind] Done in 317ms.
[dev:*remix] 💿 File changed: app\styles\tailwind.css
[dev:*remix] 💿 Rebuilding...
[dev:*remix] 💿 Rebuilt in 57ms
[dev:*miniflare] [Worker] Running esbuild in development mode
[dev:*miniflare] [mf:inf] Build succeeded
[dev:*miniflare] The "__session" cookie is not signed, but session cookies should be signed to prevent tampering on the client before they are sent back to the server. See https://remix.run/docs/en/v1/api/remix#signing-cookies for more information.
[dev:*miniflare] [mf:inf] Worker reloaded! (0.54MiB)
[dev:*miniflare] [mf:inf] Listening on :8787
[dev:*miniflare] [mf:inf] - http://172.21.0.1:8787
[dev:*miniflare] [mf:inf] - http://192.168.86.161:8787
[dev:*miniflare] [mf:inf] - http://192.168.216.1:8787
[dev:*miniflare] [mf:inf] - http://192.168.222.1:8787
[dev:*miniflare] [mf:inf] - http://127.0.0.1:8787
[dev:*miniflare] GET / 200 OK (26.21ms)
[dev:*miniflare] GET /build/_assets/tailwind-UZCJG2HW.css 200 OK (10.11ms)
[dev:*miniflare] GET /build/_shared/chunk-E7VMOUYL.js 200 OK (7.18ms)
[dev:*miniflare] GET /build/root-TFKN6SNW.js 200 OK (5.39ms)
[dev:*miniflare] GET /build/_shared/chunk-IZ266SIS.js 200 OK (10.05ms)
[dev:*miniflare] GET /build/routes/index-44ZY4T2F.js 200 OK (5.77ms)
[dev:*miniflare] GET /build/manifest-F2890140.js 200 OK (5.28ms)
[dev:*miniflare] GET /build/entry.client-JJATSL6U.js 200 OK (19.61ms)
[dev:*miniflare] GET /favicon.png 200 OK (2.07ms)
[dev:*miniflare] GET /favicon.png 200 OK (1.90ms)
[dev:*tailwind] 
[dev:*tailwind] Rebuilding...
[dev:*remix] 💿 File changed: app\routes\index.tsx
[dev:*tailwind] Done in 104ms.
[dev:*remix] 💿 Rebuilding...
[dev:*remix] 💿 File changed: app\styles\tailwind.css
[dev:*remix] 💿 Rebuilt in 68ms
[dev:*remix] 💿 Rebuilding...
[dev:*remix] 💿 Rebuilt in 63ms
[dev:*miniflare] GET / 200 OK (5.99ms)
[dev:*miniflare] GET /build/_assets/tailwind-UZCJG2HW.css 200 OK (1.35ms)
[dev:*miniflare] GET /build/root-TFKN6SNW.js 200 OK (5.45ms)
[dev:*miniflare] GET /build/_shared/chunk-IZ266SIS.js 200 OK (8.21ms)
[dev:*miniflare] GET /build/routes/index-44ZY4T2F.js 200 OK (3.84ms)
[dev:*miniflare] GET /build/_shared/chunk-E7VMOUYL.js 200 OK (7.61ms)
[dev:*miniflare] GET /build/manifest-F2890140.js 200 OK (4.05ms)
[dev:*miniflare] GET /build/entry.client-JJATSL6U.js 200 OK (4.38ms)
[dev:*miniflare] GET /favicon.png 200 OK (1.93ms)
[dev:*miniflare] GET /favicon.png 200 OK (1.22ms)
[dev:*miniflare] [Worker] Running esbuild in development mode
[dev:*miniflare] [mf:inf] Build succeeded
[dev:*miniflare] The "__session" cookie is not signed, but session cookies should be signed to prevent tampering on the client before they are sent back to the server. See https://remix.run/docs/en/v1/api/remix#signing-cookies for more information.
[dev:*miniflare] [mf:inf] Worker reloaded! (0.54MiB)
[dev:*miniflare] [Worker] Running esbuild in development mode
[dev:*miniflare] [mf:inf] Build succeeded
[dev:*miniflare] The "__session" cookie is not signed, but session cookies should be signed to prevent tampering on the client before they are sent back to the server. See https://remix.run/docs/en/v1/api/remix#signing-cookies for more information.
[dev:*miniflare] [mf:inf] Worker reloaded! (0.54MiB)
[dev:*miniflare] [mf:inf] Worker reloaded! (0B)
[dev:*miniflare] [mf:err] GET /: FetchError: No fetch handler responded and unable to proxy request to upstream: no upstream specified. Have you added a fetch event listener that responds with a Response?
[dev:*miniflare]     at EventTarget.[dispatchFetch] (C:\dev\me\remix-cloudflare-demo\node_modules\miniflare\src\modules\events.ts:224:13)
[dev:*miniflare]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[dev:*miniflare] GET / 500 Internal Server Error (56.28ms)
[dev:*miniflare] [mf:err] GET /favicon.ico: FetchError: No fetch handler responded and unable to proxy request to upstream: no upstream specified. Have you added a fetch event listener that responds with a Response?
[dev:*miniflare]     at EventTarget.[dispatchFetch] (C:\dev\me\remix-cloudflare-demo\node_modules\miniflare\src\modules\events.ts:224:13)
[dev:*miniflare]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[dev:*miniflare] GET /favicon.ico 500 Internal Server Error (7.34ms)
[dev:*miniflare] [mf:err] GET /: FetchError: No fetch handler responded and unable to proxy request to upstream: no upstream specified. Have you added a fetch event listener that responds with a Response?
[dev:*miniflare]     at EventTarget.[dispatchFetch] (C:\dev\me\remix-cloudflare-demo\node_modules\miniflare\src\modules\events.ts:224:13)
[dev:*miniflare]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[dev:*miniflare] GET / 500 Internal Server Error (3.88ms)
[dev:*miniflare] [mf:err] GET /favicon.ico: FetchError: No fetch handler responded and unable to proxy request to upstream: no upstream specified. Have you added a fetch event listener that responds with a Response?
[dev:*miniflare]     at EventTarget.[dispatchFetch] (C:\dev\me\remix-cloudflare-demo\node_modules\miniflare\src\modules\events.ts:224:13)
[dev:*miniflare]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[dev:*miniflare] GET /favicon.ico 500 Internal Server Error (5.85ms)
[dev:*miniflare] [mf:err] GET /: FetchError: No fetch handler responded and unable to proxy request to upstream: no upstream specified. Have you added a fetch event listener that responds with a Response?
[dev:*miniflare]     at EventTarget.[dispatchFetch] (C:\dev\me\remix-cloudflare-demo\node_modules\miniflare\src\modules\events.ts:224:13)
[dev:*miniflare]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[dev:*miniflare] GET / 500 Internal Server Error (2.75ms)
[dev:*miniflare] [mf:err] GET /favicon.ico: FetchError: No fetch handler responded and unable to proxy request to upstream: no upstream specified. Have you added a fetch event listener that responds with a Response?
[dev:*miniflare]     at EventTarget.[dispatchFetch] (C:\dev\me\remix-cloudflare-demo\node_modules\miniflare\src\modules\events.ts:224:13)
[dev:*miniflare]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[dev:*miniflare] GET /favicon.ico 500 Internal Server Error (3.20ms)
Terminate batch job (Y/N)? [dev:*miniflare] Terminate batch job (Y/N)? Terminate batch job (Y/N)? Terminate batch job (Y/N)? Terminate batch job (Y/N)? npm run dev:remix exited with code 1
[dev:*cypress] npm run dev:cypress exited with code 1
[dev:*miniflare] npm run dev:miniflare exited with code 1
[dev:*tailwind] npm run dev:tailwind exited with code 1
```
